# Generated by Django 2.1.1 on 2018-11-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('user_id', models.CharField(default='0000000000000000', max_length=255, unique=True)),
                ('avatar_url', models.CharField(default='http://avatal.lelewuxian.com', max_length=255)),
                ('passwd', models.CharField(max_length=255)),
                ('agent_id', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('state', models.BooleanField(default=True)),
                ('is_vip', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('is_talke', models.BooleanField(default=True)),
                ('is_robot', models.BooleanField(default=False)),
                ('last_login', models.DateField(auto_now=True)),
                ('register_time', models.DateField(auto_now_add=True)),
                ('type_1', models.CharField(max_length=255)),
                ('type_2', models.CharField(max_length=255)),
                ('type_3', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
