# Generated by Django 2.1.1 on 2018-11-02 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyBi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_m', models.CharField(default='0', max_length=50, verbose_name='历史总分')),
                ('cur_m', models.CharField(default='0', max_length=50, verbose_name='当前总分')),
                ('get_m', models.CharField(default='0', max_length=50, verbose_name='历史总下分')),
                ('recharge_lasttime', models.DateField(verbose_name='最后充值时间')),
                ('withdraw_lastime', models.DateField(verbose_name='最后下分时间')),
            ],
        ),
        migrations.AlterField(
            model_name='myusers',
            name='agent_id',
            field=models.CharField(max_length=255, verbose_name='代理id'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='avatar_url',
            field=models.CharField(default='http://avatal.lelewuxian.com', max_length=255, verbose_name='用户头像'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='用户激活'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='管理员'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='is_robot',
            field=models.BooleanField(default=False, verbose_name='机器人'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='is_talke',
            field=models.BooleanField(default=True, verbose_name='用户禁言'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='is_vip',
            field=models.IntegerField(default=0, verbose_name='vip'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='last_login',
            field=models.DateField(auto_now=True, verbose_name='最后登陆时间'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='passwd',
            field=models.CharField(max_length=255, verbose_name='用户密码'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='register_time',
            field=models.DateField(auto_now_add=True, verbose_name='注册时间'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='state',
            field=models.BooleanField(default=True, verbose_name='用户状态'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='user_id',
            field=models.CharField(default='0000000000000000', max_length=255, unique=True, verbose_name='用户id'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='username',
            field=models.CharField(max_length=255, unique=True, verbose_name='用户名'),
        ),
        migrations.AddField(
            model_name='mybi',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
