# Generated by Django 2.1.1 on 2018-12-04 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0004_remove_myusers_passwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='nickname',
            field=models.CharField(default='lalla', max_length=255, verbose_name='昵称'),
        ),
    ]
