# Generated by Django 2.1.1 on 2018-12-04 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0006_auto_20181204_1357'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAgent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_id', models.CharField(default='000000000000', max_length=20, unique=True, verbose_name='代理id')),
                ('agent_name', models.CharField(default='XX公司', max_length=50, unique=True, verbose_name='代理名')),
                ('father_agent', models.CharField(default='0', max_length=20, verbose_name='代理id')),
                ('pre_agent', models.CharField(default='0', max_length=20, verbose_name='上一级代理id')),
                ('next_agent', models.CharField(default='0', max_length=20, verbose_name='下一级代理id')),
                ('agent_percent', models.IntegerField(default=10, verbose_name='代理分成比例%')),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_id', models.CharField(default='0000', max_length=5, unique=True, verbose_name='房间id号')),
                ('room_name', models.CharField(default='百丽宫', max_length=20, unique=True, verbose_name='房间名')),
                ('is_active', models.BooleanField(default=True, verbose_name='房间开启状态')),
                ('is_public', models.BooleanField(default=True, verbose_name='房间是否公开')),
                ('is_vip', models.BooleanField(default=False, verbose_name='房间是否属于vip')),
                ('passwd', models.CharField(default='123456', max_length=10, verbose_name='vip房间密码')),
                ('agent_id', models.CharField(default='000000000000', max_length=20, verbose_name='房间所属于agent')),
                ('room_admin', models.CharField(default='root', max_length=20, verbose_name='房间管理员')),
            ],
        ),
    ]
