# Generated by Django 2.1.1 on 2018-12-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0008_auto_20181204_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='rooms',
            name='room_video',
            field=models.CharField(default='ws://lelewuxian.com', max_length=255, verbose_name='房间视频地址'),
        ),
    ]
