# Generated by Django 2.1.1 on 2018-12-05 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0009_rooms_room_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rooms',
            name='room_id',
            field=models.CharField(default='room001', max_length=10, unique=True, verbose_name='房间id号'),
        ),
    ]
