# Generated by Django 2.1.1 on 2018-12-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0010_auto_20181205_1100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myusers',
            name='avatar_url',
            field=models.CharField(default='', max_length=255, verbose_name='用户头像'),
        ),
    ]
