# Generated by Django 2.1.1 on 2019-01-02 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0013_auto_20181231_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='myagent',
            name='username',
            field=models.CharField(default='root', max_length=50, unique=True, verbose_name='用户名'),
        ),
    ]
