# Generated by Django 2.2.dev20190101154022 on 2019-01-04 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0014_myagent_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mybi',
            name='recharge_lasttime',
            field=models.CharField(max_length=50, verbose_name='最后充值时间'),
        ),
        migrations.AlterField(
            model_name='mybi',
            name='withdraw_lastime',
            field=models.CharField(max_length=50, verbose_name='最后下分时间'),
        ),
    ]
