# Generated by Django 2.2.dev20190101154022 on 2019-01-28 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0016_auto_20190123_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.CharField(max_length=50, verbose_name='时间')),
                ('opusername', models.CharField(max_length=50, verbose_name='操作人')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('operator', models.CharField(max_length=5, verbose_name='(上分/下分)')),
                ('content', models.CharField(max_length=50, verbose_name='操作内容')),
            ],
        ),
    ]
