# Generated by Django 2.2.dev20190101154022 on 2019-01-28 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0017_chargehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargehistory',
            name='content',
            field=models.CharField(max_length=500, verbose_name='操作内容'),
        ),
        migrations.AlterField(
            model_name='chargehistory',
            name='operator',
            field=models.CharField(max_length=10, verbose_name='(上分/下分)'),
        ),
    ]
