# Generated by Django 2.2.dev20190101154022 on 2019-02-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0018_auto_20190128_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='combi',
            name='ls_com_total',
            field=models.IntegerField(default=0),
        ),
    ]
