# Generated by Django 2.2.dev20190101154022 on 2019-02-16 05:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0019_combi_ls_com_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbi',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间'),
        ),
    ]
