# Generated by Django 2.2.dev20190101154022 on 2019-02-16 06:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0020_auto_20190216_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chargehistory',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='combi',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间'),
        ),
    ]
