# Generated by Django 2.2.dev20190101154022 on 2019-02-16 07:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0021_auto_20190216_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combi',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 16, 15, 42, 6, 148398), verbose_name='时间'),
        ),
    ]
