# Generated by Django 2.2.dev20190101154022 on 2019-02-17 03:11

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0022_auto_20190216_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combi',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2019, 2, 17, 11, 11, 37, 174173), verbose_name='时间'),
        ),
        migrations.AlterField(
            model_name='useroperator',
            name='xiazhu_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='下注时间'),
        ),
    ]
