# Generated by Django 2.2.dev20190101154022 on 2019-02-17 03:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myauth', '0023_auto_20190217_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combi',
            name='date_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间'),
        ),
    ]
